// Package apispec carries the generated OpenAPI document for the proxy's
// REST API (RD-1166). swagger.json / swagger.yaml are GENERATED by
// `make api-spec` (swag v2, pinned in go.mod tools) from the swaggo
// annotations on the handlers — do not edit them by hand. The committed
// copy is what gets embedded into the binary and served at GET /openapi.json,
// and what the docs site publishes; CI regenerates and fails on drift.
package apispec

import _ "embed"

// JSON is the OpenAPI 3.1 document, as generated by `make api-spec`.
//
//go:embed swagger.json
var JSON []byte
