// Identity bootstrap via @0xpolygonid/js-sdk.
//
// The SDK's IdentityWallet handles the heavy lifting (BabyJubJub keygen,
// Auth claim, three identity trees, genesis state, DID derivation). We
// wrap it in a thin CLI + persistence layer.
//
// Persistence shape (JSON, mode 0600):
//
//   {
//     "version":     1,
//     "did":         "did:iden3:privado:main:...",
//     "state":       "0x...",
//     "created_at":  "2026-05-19T...",
//     "wallet_state": {
//       "babyjub_seed_hex": "...64 hex chars (32 bytes)...",
//       "did_method":     "iden3",
//       "did_blockchain": "privado",
//       "did_network":    "main"
//     }
//   }
//
// The BabyJubJub seed is the only persistent secret. `createIdentity` is
// deterministic given (seed, method, blockchain, networkId, revocation
// nonce=0) — passing the same persisted seed on a later `auth` run
// reproduces the same DID, the same trees, and the same genesis state.
// Verified against
// node_modules/@0xpolygonid/js-sdk/dist/node/esm/index.js lines
// 15426-15517 ("opts.seed = opts.seed ?? getRandomBytes2(32);
// const { authClaim, pubKey } = await this.createAuthCoreClaim(revNonce,
// opts.seed); ... identifier = Id19.idGenesisFromIdenState(didType,
// currentState.bigInt())"). Same seed → same currentState → same DID.
//
// Security: the seed grants full control over the identity. The file is
// chmod 0600. README emphasises storing it in a secret manager.

import { randomBytes } from "node:crypto";
import { writeFile, readFile, chmod } from "node:fs/promises";

import {
  IdentityWallet,
  CredentialWallet,
  KMS,
  KmsKeyType,
  BjjProvider,
  Sec256k1Provider,
  InMemoryDataSource,
  InMemoryPrivateKeyStore,
  InMemoryMerkleTreeStorage,
  CredentialStorage,
  IdentityStorage,
  type IDataStorage,
  type Identity,
  type Profile,
  defaultEthConnectionConfig,
  EthStateStorage,
  CredentialStatusType,
  CredentialStatusResolverRegistry,
  RHSResolver,
  core,
} from "@0xpolygonid/js-sdk";

export interface IdentityFile {
  version: 1;
  did: string;
  state: string;
  created_at: string;
  notes: string;
  wallet_state: WalletStateBlob;
}

// WalletStateBlob captures the persistent material we need to rebuild
// the wallet on a later run. The BabyJubJub seed is the only secret;
// every other piece of identity state is derived from it.
export interface WalletStateBlob {
  // Hex-encoded 32-byte BabyJubJub seed (no 0x prefix). Same seed →
  // same DID + state via IdentityWallet.createIdentity.
  babyjub_seed_hex: string;
  // DID-method tuple. Pinned here so an operator who points the
  // emulator at a different state contract gets a clear error rather
  // than a mysteriously-failing on-chain lookup.
  did_method: "iden3";
  did_blockchain: "privado";
  did_network: "main" | "test";
}

const FILE_MODE = 0o600;
const FILE_VERSION = 1 as const;
const SEED_BYTES = 32;

// PrivadoMainStateRPC is the public RPC the iden3 SDK's EthStateStorage
// reads to compute gist proofs. Keeping it local so an offline
// `identity init` works without it; only `auth` needs network.
const PrivadoMainStateRPC = "https://rpc-mainnet.privado.id";
// PrivadoMainStateContract is the canonical Privado mainnet state
// contract. Mirrors privacy-proxy's internal/auth/privado.go:33.
const PrivadoMainStateContract = "0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896";

export async function runIdentityInit(outPath: string): Promise<void> {
  // 1. Generate the BJJ seed first; the SDK uses it deterministically.
  const seed = randomBytes(SEED_BYTES);

  // 2. Build a wallet pinned to that seed (KMS gets it pre-imported by
  //    BjjProvider via the createIdentity call below).
  const { wallet } = buildWallet();

  // 3. Create the identity. genesisPublishingDisabled=true keeps this
  //    offline — no RHS / state-contract round-trip from `init`. The
  //    operator publishes manually after the file is written.
  const { did } = await wallet.createIdentity({
    method: core.DidMethod.Iden3,
    blockchain: core.Blockchain.Privado,
    networkId: core.NetworkId.Main,
    seed,
    revocationOpts: {
      type: CredentialStatusType.Iden3ReverseSparseMerkleTreeProof,
      // `id` is the RHS URL embedded in the credential status. We
      // never resolve it from the emulator (the AuthV2 circuit doesn't
      // need credential revocation status), but the SDK requires a
      // non-empty string. Use the canonical Privado RHS URL.
      id: "https://rhs-staging.polygonid.me",
      nonce: 0,
      genesisPublishingDisabled: true,
    },
  });

  const stateHex = await currentStateHex(wallet, did);

  const idf: IdentityFile = {
    version: FILE_VERSION,
    did: did.string(),
    state: stateHex,
    created_at: new Date().toISOString(),
    notes:
      "Generated by wallet-emulator-js (Track A / RD-948). Register the (DID, state) pair on the Privado state contract before using this identity for auth. See tools/wallet-emulator-js/README.md.",
    wallet_state: {
      babyjub_seed_hex: seed.toString("hex"),
      did_method: "iden3",
      did_blockchain: "privado",
      did_network: "main",
    },
  };

  await writeFile(outPath, JSON.stringify(idf, null, 2));
  await chmod(outPath, FILE_MODE);

  // stdout is intentionally minimal-but-useful: operators tail it via
  // CI logs and we don't want surprises. The actual secret never lands
  // in stdout — only the file path does.
  console.log(`Created identity:`);
  console.log(`  DID:   ${idf.did}`);
  console.log(`  State: ${idf.state}`);
  console.log(`  File:  ${outPath} (mode 0600)`);
  console.log();
  console.log(`NEXT: register the (DID, state) pair on the Privado state contract.`);
  console.log(`      Until that's done the proxy verifier will reject every JWZ this identity produces.`);
  console.log(`      See tools/wallet-emulator-js/README.md → 'On-chain registration'.`);
}

export async function runIdentityShow(path: string): Promise<void> {
  const idf = await loadIdentity(path);
  console.log(`DID:        ${idf.did}`);
  console.log(`State:      ${idf.state}`);
  console.log(`Created at: ${idf.created_at}`);
  console.log(`Schema ver: ${idf.version}`);
  if (idf.notes) {
    console.log(`Notes:      ${idf.notes}`);
  }
}

export async function loadIdentity(path: string): Promise<IdentityFile> {
  const raw = await readFile(path, "utf8");
  const parsed = JSON.parse(raw) as Partial<IdentityFile>;
  if (parsed.version !== FILE_VERSION) {
    throw new Error(
      `unsupported identity-file version ${String(parsed.version)} (this binary expects ${FILE_VERSION}); regenerate with \`identity init\``,
    );
  }
  if (
    !parsed.did ||
    !parsed.state ||
    !parsed.wallet_state?.babyjub_seed_hex ||
    parsed.wallet_state.babyjub_seed_hex.length !== SEED_BYTES * 2
  ) {
    throw new Error(
      `identity file ${path} is missing required fields (did / state / wallet_state.babyjub_seed_hex)`,
    );
  }
  return parsed as IdentityFile;
}

// HydratedWallet is the bundle a caller needs to drive AuthHandler:
// the IdentityWallet, the CredentialWallet (AuthHandler reaches it via
// IdentityWallet.credentialWallet but ProofService takes both), the
// data storage (for ProofService gist proof access), the DID parsed
// from the persisted file, and the KMS (only exposed in case the
// caller wants to introspect; not required for the auth flow).
export interface HydratedWallet {
  wallet: IdentityWallet;
  credentialWallet: CredentialWallet;
  dataStorage: IDataStorage;
  kms: KMS;
  did: core.DID;
  identity: IdentityFile;
}

// hydrateWalletFromFile rebuilds an in-memory IdentityWallet from the
// persisted seed. Same seed → identical DID + state. Network is only
// touched lazily by ProofService when it asks EthStateStorage for the
// gist proof; `init` never does that, `auth` does.
//
// Important: `createIdentity` is the ONLY public path that takes a
// seed today (verified against
// node_modules/@0xpolygonid/js-sdk/dist/types/identity/identity-wallet.d.ts
// — AuthBJJCredentialCreationOptions.seed: Uint8Array). There's no
// "loadIdentity(did)" symmetric API in 1.27.x. We reuse `createIdentity`
// as the rehydration primitive; the SDK short-circuits to the existing
// credential if it finds one matching (x,y) in the in-memory store
// (bundle line 15474), but since the in-memory store is fresh on every
// run, it always rebuilds the trees + credential — which is cheap.
export async function hydrateWalletFromFile(
  identityPath: string,
  stateRpcURL: string | undefined,
): Promise<HydratedWallet> {
  const idf = await loadIdentity(identityPath);
  const seed = Buffer.from(idf.wallet_state.babyjub_seed_hex, "hex");
  if (seed.length !== SEED_BYTES) {
    throw new Error(
      `decoded BJJ seed has wrong length: got ${seed.length} bytes, want ${SEED_BYTES}`,
    );
  }

  const { wallet, credentialWallet, dataStorage, kms } = buildWallet(stateRpcURL);

  // Recompute the identity from the persisted seed. Must match the
  // method/blockchain/networkId encoded in the persisted file so the
  // generated DID matches `idf.did`.
  const { did } = await wallet.createIdentity({
    method: core.DidMethod.Iden3,
    blockchain: core.Blockchain.Privado,
    networkId: core.NetworkId.Main,
    seed,
    revocationOpts: {
      type: CredentialStatusType.Iden3ReverseSparseMerkleTreeProof,
      id: "https://rhs-staging.polygonid.me",
      nonce: 0,
      genesisPublishingDisabled: true,
    },
  });

  // Sanity check: rehydrated DID must match the persisted one. If it
  // doesn't, the identity file was generated against a different SDK
  // version or different method/network tuple — bail loudly.
  if (did.string() !== idf.did) {
    throw new Error(
      `rehydrated DID ${did.string()} does not match persisted DID ${idf.did}; ` +
        `seed/method/network mismatch — regenerate with \`identity init\` against the current SDK`,
    );
  }
  const rehydratedState = await currentStateHex(wallet, did);
  if (rehydratedState !== idf.state) {
    throw new Error(
      `rehydrated state ${rehydratedState} does not match persisted state ${idf.state}; ` +
        `the SDK appears to have changed its genesis-derivation algorithm — regenerate the identity`,
    );
  }

  return { wallet, credentialWallet, dataStorage, kms, did, identity: idf };
}

// buildWallet wires the SDK's in-memory data sources + KMS + key
// providers. If `stateRpcURL` is set the EthStateStorage is configured
// against Privado mainnet — required for `auth` (gist proof). For
// `identity init` we pass undefined and the storage points at the
// default localhost RPC, which is fine because `init` never calls it.
function buildWallet(stateRpcURL?: string): {
  wallet: IdentityWallet;
  credentialWallet: CredentialWallet;
  dataStorage: IDataStorage;
  kms: KMS;
} {
  const kms = new KMS();
  const bjjKeyStore = new InMemoryPrivateKeyStore();
  kms.registerKeyProvider(KmsKeyType.BabyJubJub, new BjjProvider(KmsKeyType.BabyJubJub, bjjKeyStore));
  kms.registerKeyProvider(KmsKeyType.Secp256k1, new Sec256k1Provider(KmsKeyType.Secp256k1, bjjKeyStore));

  const ethConfig = {
    ...defaultEthConnectionConfig,
    url: stateRpcURL ?? PrivadoMainStateRPC,
    contractAddress: PrivadoMainStateContract,
    chainId: 21000, // Privado main chainId
  };

  const dataStorage: IDataStorage = {
    credential: new CredentialStorage(new InMemoryDataSource()),
    identity: new IdentityStorage(new InMemoryDataSource<Identity>(), new InMemoryDataSource<Profile>()),
    mt: new InMemoryMerkleTreeStorage(40),
    states: new EthStateStorage(ethConfig),
  };

  // CredentialWallet needs a revocation-status resolver registry. The
  // RHS resolver covers Iden3ReverseSparseMerkleTreeProof (which is
  // what `createIdentity` registers above). AuthHandler doesn't
  // actually fetch revocation status for AuthV2 — but the wallet
  // constructor expects the registry to be present.
  const statusRegistry = new CredentialStatusResolverRegistry();
  statusRegistry.register(
    CredentialStatusType.Iden3ReverseSparseMerkleTreeProof,
    new RHSResolver(dataStorage.states),
  );

  const credentialWallet = new CredentialWallet(dataStorage, statusRegistry);
  const wallet = new IdentityWallet(kms, dataStorage, credentialWallet);
  return { wallet, credentialWallet, dataStorage, kms };
}

async function currentStateHex(wallet: IdentityWallet, did: core.DID): Promise<string> {
  const treeState = await wallet.getDIDTreeModel(did);
  return treeState.state.hex();
}
