// Identity bootstrap via @0xpolygonid/js-sdk.
//
// The SDK's IdentityWallet handles the heavy lifting (BabyJubJub keygen,
// Auth claim, three identity trees, genesis state, DID derivation). We
// wrap it in a thin CLI + persistence layer.
//
// Persistence shape (JSON, mode 0600):
//
//   {
//     "version":     1,
//     "did":         "did:iden3:privado:main:...",
//     "state":       "0x...",
//     "created_at":  "2026-05-19T...",
//     "wallet_state": {
//       "...SDK-internal state blobs (encrypted keys, claim tree dumps, ...)..."
//     }
//   }
//
// The "wallet_state" blob is whatever the SDK's DataSource serialises.
// We keep it opaque from the operator's perspective; rotation always
// means `identity init` again + re-registering the new state on-chain.

import { writeFile, readFile, chmod } from "node:fs/promises";

import {
  // High-level wallet types from @0xpolygonid/js-sdk
  IdentityWallet,
  CredentialWallet,
  KMS,
  KmsKeyType,
  BjjProvider,
  Sec256k1Provider,
  InMemoryDataSource,
  InMemoryPrivateKeyStore,
  InMemoryMerkleTreeStorage,
  // Iden3 primitives (re-exported by the SDK)
  CredentialStorage,
  IdentityStorage,
  type IDataStorage,
  type Identity,
  type Profile,
  byteEncoder,
  defaultEthConnectionConfig,
  EthStateStorage,
  // DID method / blockchain / network enums
  core,
} from "@0xpolygonid/js-sdk";

export interface IdentityFile {
  version: 1;
  did: string;
  state: string;
  created_at: string;
  notes: string;
  // The SDK's internal state. Opaque — touching this manually breaks
  // the identity. Operators rotate by running `identity init` again.
  wallet_state: WalletStateBlob;
}

// WalletStateBlob captures the SDK's in-memory state that we need to
// re-hydrate the wallet on subsequent `auth` runs. The exact shape
// depends on the SDK version we ship against (@0xpolygonid/js-sdk
// 1.27.x); bump `version` in the parent file when the format changes.
export interface WalletStateBlob {
  // Hex-encoded BabyJubJub private key (32 bytes). The SDK regenerates
  // identity / claim trees / state deterministically from this seed
  // plus the method / blockchain / networkId tuple, so this single
  // field is sufficient to restore the wallet.
  babyjub_private_key: string;
  // DID-method tuple. Pinned here so an operator who points the
  // emulator at a different state contract (e.g. Privado test) gets a
  // clear error rather than a mysteriously-failing on-chain lookup.
  did_method: "iden3";
  did_blockchain: "privado";
  did_network: "main" | "test";
}

const FILE_MODE = 0o600;
const FILE_VERSION = 1 as const;

export async function runIdentityInit(outPath: string): Promise<void> {
  const { wallet, dataStorage } = await buildEmptyWallet();

  // Create a fresh identity. The SDK generates the BabyJubJub keypair
  // inside the KMS (deterministic from the seed it picks; we then
  // serialise the seed for persistence below). It also builds the
  // claims / revocation / roots merkle trees and computes the genesis
  // state.
  const { did, credential: _authBJJCredential } = await wallet.createIdentity({
    method: core.DidMethod.Iden3,
    blockchain: core.Blockchain.Privado,
    networkId: core.NetworkId.Main,
    // The seed param accepts a 32-byte random Buffer; passing
    // `undefined` lets the SDK generate one and store it in the KMS.
    seed: undefined,
    revocationOpts: {
      type: 0, // SparseMerkleTreeProof — default revocation tree shape.
      id: "rhsUrl-not-used-in-this-emulator",
    },
  });

  const stateHex = await currentStateHex(wallet, did);

  const idf: IdentityFile = {
    version: FILE_VERSION,
    did: did.string(),
    state: stateHex,
    created_at: new Date().toISOString(),
    notes:
      "Generated by wallet-emulator-js (Track A / RD-948). Register the (DID, state) pair on the Privado state contract before using this identity for auth. See tools/wallet-emulator-js/README.md.",
    wallet_state: await exportWalletState(dataStorage),
  };

  await writeFile(outPath, JSON.stringify(idf, null, 2));
  await chmod(outPath, FILE_MODE);

  console.log(`Created identity:`);
  console.log(`  DID:   ${idf.did}`);
  console.log(`  State: ${idf.state}`);
  console.log(`  File:  ${outPath} (mode 0600)`);
  console.log();
  console.log(`NEXT: register the (DID, state) pair on the Privado state contract.`);
  console.log(`      Until that's done the proxy verifier will reject every JWZ this identity produces.`);
  console.log(`      See tools/wallet-emulator-js/README.md → 'On-chain registration'.`);
}

export async function runIdentityShow(path: string): Promise<void> {
  const idf = await loadIdentity(path);
  console.log(`DID:        ${idf.did}`);
  console.log(`State:      ${idf.state}`);
  console.log(`Created at: ${idf.created_at}`);
  console.log(`Schema ver: ${idf.version}`);
  if (idf.notes) {
    console.log(`Notes:      ${idf.notes}`);
  }
}

export async function loadIdentity(path: string): Promise<IdentityFile> {
  const raw = await readFile(path, "utf8");
  const parsed = JSON.parse(raw) as Partial<IdentityFile>;
  if (parsed.version !== FILE_VERSION) {
    throw new Error(
      `unsupported identity-file version ${String(parsed.version)} (this binary expects ${FILE_VERSION}); regenerate with \`identity init\``,
    );
  }
  if (!parsed.did || !parsed.state || !parsed.wallet_state?.babyjub_private_key) {
    throw new Error(`identity file ${path} is missing required fields (did / state / wallet_state.babyjub_private_key)`);
  }
  return parsed as IdentityFile;
}

// buildEmptyWallet wires the SDK's in-memory data sources + KMS + key
// providers for a fresh wallet. Phase 1b will replace InMemoryDataSource
// with a file-backed equivalent so multiple `auth` invocations against
// the same identity file don't pay the proof-tree rebuild cost.
async function buildEmptyWallet(): Promise<{ wallet: IdentityWallet; dataStorage: IDataStorage }> {
  const kms = new KMS();
  const bjjKeyStore = new InMemoryPrivateKeyStore();
  kms.registerKeyProvider(KmsKeyType.BabyJubJub, new BjjProvider(KmsKeyType.BabyJubJub, bjjKeyStore));
  kms.registerKeyProvider(KmsKeyType.Secp256k1, new Sec256k1Provider(KmsKeyType.Secp256k1, bjjKeyStore));

  const dataStorage: IDataStorage = {
    credential: new CredentialStorage(new InMemoryDataSource()),
    identity: new IdentityStorage(new InMemoryDataSource<Identity>(), new InMemoryDataSource<Profile>()),
    mt: new InMemoryMerkleTreeStorage(40),
    // states is the EthStateStorage configured against the Privado main
    // state contract. The CLI will only HIT this on `auth` runs (when
    // building the gist proof); `identity init` doesn't need network.
    states: new EthStateStorage(defaultEthConnectionConfig),
  };

  const credWallet = new CredentialWallet(dataStorage);
  const wallet = new IdentityWallet(kms, dataStorage, credWallet);
  return { wallet, dataStorage };
}

async function currentStateHex(wallet: IdentityWallet, did: core.DID): Promise<string> {
  const treeState = await wallet.getDIDTreeModel(did);
  // treeState.state is a Hash (32 bytes). Stringify via the SDK helper
  // which produces a 0x-prefixed lowercase hex value identical to what
  // the proxy verifier resolver consumes on-chain.
  return treeState.state.hex();
}

async function exportWalletState(dataStorage: IDataStorage): Promise<WalletStateBlob> {
  // Serialise the BabyJubJub private key so we can rehydrate the wallet
  // for `auth` runs. The SDK's KMS doesn't expose the raw seed via
  // public API as of 1.27.x; this is the Phase 1b wiring point — we
  // probably need to switch from InMemoryPrivateKeyStore to a
  // filesystem-backed PrivateKeyStore that we control.
  //
  // TODO(RD-948 Phase A-1b): wire the persistent KMS key store so the
  //                           BabyJub private key is recoverable across
  //                           `identity init` → `auth` invocations.
  void dataStorage;
  return {
    babyjub_private_key: "TODO-phase-1b-persist-bjj-seed",
    did_method: "iden3",
    did_blockchain: "privado",
    did_network: "main",
  };
}
