package server

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"privacy-proxy/internal/governance"
	"privacy-proxy/internal/rbac"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// setupE2EGovernanceServer wires up a dummy endpoint into an existing server instance
func setupE2EGovernanceServer(t *testing.T, srv *testServerRBAC, org *rbac.Organization) (string, string) {
	
	// Create required users
	requesterID := uuid.New().String()
	approverID := uuid.New().String()
	
	for _, id := range []string{requesterID, approverID} {
		require.NoError(t, srv.db.CreateUser(context.Background(), &rbac.User{
			ID:         id,
			ExternalID: id + "-did",
			CreatedAt:  time.Now(),
			UpdatedAt:  time.Now(),
		}))
	}

	// Re-initialize engine
	srv.governanceEngine = governance.NewEngine(srv.db, srv.Server, nil)

	// Add dummy route for testing applier with middleware
	srv.router.POST("/api/orgs/:org_id/dummy-resource/:address",
		func(c *gin.Context) {
			// Mock auth
			c.Set("user_id", requesterID)
			c.Set("admin_user_id", requesterID)
			c.Set("active_org_id", c.Param("org_id"))
			c.Next()
		},
		srv.governanceMiddleware("createContractGrant"), // Must match a known type to avoid 500
		func(c *gin.Context) {
			c.JSON(http.StatusCreated, gin.H{"status": "created"})
		},
	)

	return requesterID, approverID
}

func TestE2EGovernanceFlow(t *testing.T) {
	srv := setupTestServerForRBAC(t)
	org := createTestOrgWithGovernance(t, srv.db, true, 1)

	// Create real contract and group so the Applier can successfully create the grant
	contractID := uuid.New().String()
	require.NoError(t, srv.db.CreateContract(context.Background(), &rbac.Contract{
		ID:        contractID,
		OrgID:     org.ID,
		Address:   "0x123",
		Name:      "Test Contract",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}))

	groupID := uuid.New().String()
	require.NoError(t, srv.db.CreateGroup(context.Background(), &rbac.Group{
		ID:        groupID,
		OrgID:     org.ID,
		Name:      "Test Group",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}))
	
	_, approverID := setupE2EGovernanceServer(t, srv, org)

	t.Run("SubmitAndApprove", func(t *testing.T) {
		// 1. Submit request via dummy endpoint
		// The dummy endpoint must use real payload for createContractGrant
		body := map[string]any{
			"contract_address": "0x123",
			"group_id":         groupID,
			"claims":           []string{"read"},
		}
		jsonBody, _ := json.Marshal(body)

		req := httptest.NewRequest(http.MethodPost, "/api/orgs/"+org.ID+"/dummy-resource/0x123", bytes.NewReader(jsonBody))
		req.Header.Set("Content-Type", "application/json")
		w := httptest.NewRecorder()
		srv.router.ServeHTTP(w, req)

		require.Equal(t, http.StatusAccepted, w.Code)
		
		var response map[string]any
		require.NoError(t, json.Unmarshal(w.Body.Bytes(), &response))
		requestID := response["request_id"].(string)

		// 2. Fetch requests via API
		reqList := httptest.NewRequest(http.MethodGet, "/api/admin/orgs/"+org.ID+"/governance/requests", nil)
		wList := httptest.NewRecorder()
		
		// To test the admin APIs properly, we must wrap them with a mock auth middleware 
		// because the real routes check for `c.GetString("user_id")` generated by JWT.
		testApi := srv.router.Group("/e2e-admin")
		testApi.Use(func(c *gin.Context) {
			c.Set("user_id", approverID)
			c.Set("admin_user_id", approverID)
			c.Set("active_org_id", org.ID)
			c.Set("claims", []string{"approve"})
			c.Next()
		})
		testApi.GET("/orgs/:org_id/governance/requests", srv.listGovernanceRequests)
		testApi.POST("/orgs/:org_id/governance/requests/:request_id/approve", srv.approveGovernanceRequest)

		// Get all requests
		reqList = httptest.NewRequest(http.MethodGet, "/e2e-admin/orgs/"+org.ID+"/governance/requests", nil)
		wList = httptest.NewRecorder()
		srv.router.ServeHTTP(wList, reqList)

		// Should see our pending request
		require.Equal(t, http.StatusOK, wList.Code)

		// Verify it's correctly captured in DB BEFORE deciding
		dbReqBefore, _ := srv.db.GetApprovalRequest(context.Background(), requestID)
		t.Logf("DB Payload before decide: %s", string(dbReqBefore.Payload))

		// 3. Admin user decides 'approve'
		decisionBody := map[string]any{
			"reason": "Looks good to me",
		}
		jsonDecision, _ := json.Marshal(decisionBody)
		reqDecide := httptest.NewRequest(http.MethodPost, "/e2e-admin/orgs/"+org.ID+"/governance/requests/"+requestID+"/approve", bytes.NewReader(jsonDecision))
		reqDecide.Header.Set("Content-Type", "application/json")
		wDecide := httptest.NewRecorder()
		srv.router.ServeHTTP(wDecide, reqDecide)

		t.Logf("Approve response: %s", wDecide.Body.String())
		require.Equal(t, http.StatusOK, wDecide.Code)
		
		var decisionResp map[string]any
		require.NoError(t, json.Unmarshal(wDecide.Body.Bytes(), &decisionResp))
		assert.Equal(t, "approved", decisionResp["request"].(map[string]any)["status"])

		// 4. Verify request is applied successfully in DB
		dbReq, err := srv.db.GetApprovalRequest(context.Background(), requestID)
		require.NoError(t, err)
		assert.Equal(t, rbac.StatusApproved, dbReq.Status)
	})
}
