package server

import (
	"fmt"
	"sort"
	"strings"
)

// BuildInventory renders the auditor-facing API_ENDPOINTS.md content from the
// live gin route table (RD-1166): every registered route grouped by the
// canonical operation it maps to, per-method totals, and the alias/mirror
// mounts. `all` is the full route table (dev builds), `prod` the
// production-registered subset. Returns the markdown and the distinct-operation
// count (for the caller's console summary).
//
// Output MUST be deterministic so CI can regenerate and fail on drift: every
// map iterated below is sorted by a stable key before it feeds output (the
// determinism itself is exercised by TestBuildInventory_Deterministic). The
// generator lives in package server (not cmd/api-inventory) so that test runs
// in the `./internal/...` CI job and the pre-push hook — a test under cmd/
// would never execute (RD-1190).
func BuildInventory(all, prod []RouteEntry) (string, int) {
	prodSet := make(map[string]bool, len(prod))
	for _, r := range prod {
		prodSet[r.Method+" "+r.Path] = true
	}

	var b strings.Builder
	b.WriteString("# Privacy Proxy — REST API Endpoint Inventory\n\n")
	b.WriteString("Generated from the live gin route table by `make api-inventory` — do not edit by hand.\n")
	b.WriteString("The machine-readable API specification is the OpenAPI document (`internal/server/apispec/swagger.json`,\n")
	b.WriteString("served at `GET /openapi.json`, generated by `make api-spec`).\n\n")

	// Group registered routes by canonical operation.
	type op struct {
		methods map[string]bool
		devOnly bool
	}
	ops := map[string]*op{} // canonical path -> op
	type aliasRow struct{ method, path, canonical, kind string }
	var aliases []aliasRow
	methodTotals := map[string]int{}

	for _, r := range all {
		methodTotals[r.Method]++
		cls := CanonicalizeRoute(r.Path)
		if cls.Kind != RouteKindCanonical {
			aliases = append(aliases, aliasRow{r.Method, r.Path, cls.Canonical, cls.Kind})
			continue
		}
		if ops[cls.Canonical] == nil {
			ops[cls.Canonical] = &op{methods: map[string]bool{}, devOnly: true}
		}
		o := ops[cls.Canonical]
		o.methods[r.Method] = true
		if prodSet[r.Method+" "+r.Path] {
			o.devOnly = false
		}
	}

	// Summary.
	b.WriteString("## Totals\n\n")
	fmt.Fprintf(&b, "- **Registered routes:** %d (production registers %d; the remainder are dev-build-only)\n", len(all), len(prod))
	fmt.Fprintf(&b, "- **Distinct operations (canonical paths):** %d — alias mounts (legacy `/api/*`, `/eth`, root auth, JSON-RPC `/`, impersonation mirrors) collapse onto these\n", len(ops))
	b.WriteString("- **Registered routes by method:** ")
	var methods []string
	for m := range methodTotals {
		methods = append(methods, m)
	}
	sort.Slice(methods, func(i, j int) bool {
		// Tie-break by name: several methods share a count (the .Any()
		// mounts), and without this the order is map-iteration randomness —
		// which the CI drift check (regenerate + git diff) rightly rejects.
		if methodTotals[methods[i]] != methodTotals[methods[j]] {
			return methodTotals[methods[i]] > methodTotals[methods[j]]
		}
		return methods[i] < methods[j]
	})
	var parts []string
	for _, m := range methods {
		parts = append(parts, fmt.Sprintf("%s %d", m, methodTotals[m]))
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString("\n\n")
	b.WriteString("Note: gin registers `.Any()` mounts (the impersonation JSON-RPC mirrors) as one route per HTTP method, so per-method totals count each of those mounts several times.\n\n")

	// Distinct operations table.
	b.WriteString("## Distinct operations\n\n")
	b.WriteString("| Method(s) | Path | Auth | Notes |\n|---|---|---|---|\n")
	var canonPaths []string
	for p := range ops {
		canonPaths = append(canonPaths, p)
	}
	sort.Strings(canonPaths)
	for _, p := range canonPaths {
		o := ops[p]
		var ms []string
		for m := range o.methods {
			ms = append(ms, m)
		}
		sort.Strings(ms)
		if len(ms) >= 7 { // .Any() mount
			ms = []string{"ANY"}
		}
		note := ""
		if o.devOnly {
			note = "dev builds only (not registered in production)"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", strings.Join(ms, ", "), p, AuthForPath(p), note)
	}

	// Alias table.
	b.WriteString("\n## Alias & mirror mounts (registered, collapsed above)\n\n")
	b.WriteString("| Method | Path | Documented as | Kind |\n|---|---|---|---|\n")
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].path != aliases[j].path {
			return aliases[i].path < aliases[j].path
		}
		return aliases[i].method < aliases[j].method
	})
	for _, a := range aliases {
		fmt.Fprintf(&b, "| %s | `%s` | `%s` | %s |\n", a.method, a.path, a.canonical, a.kind)
	}

	return b.String(), len(ops)
}
