// Package broadcast provides types and parsing for Foundry broadcast files.
package broadcast

// BroadcastFile represents a Foundry broadcast JSON file.
// These files are generated by `forge script --broadcast` and contain
// details about all transactions executed during the script.
type BroadcastFile struct {
	Transactions []Transaction `json:"transactions"`
	Chain        int           `json:"chain"`
	Commit       string        `json:"commit"`
	Timestamp    int64         `json:"timestamp"`
}

// Transaction represents a single transaction in a Foundry broadcast file.
type Transaction struct {
	Hash                string               `json:"hash"`
	Type                string               `json:"transactionType"` // "CREATE", "CREATE2", "CALL"
	ContractName        string               `json:"contractName"`
	ContractAddress     string               `json:"contractAddress"`
	Function            string               `json:"function"`
	Arguments           []any                `json:"arguments"`
	AdditionalContracts []AdditionalContract `json:"additionalContracts"`
	IsFixedGasLimit     bool                 `json:"isFixedGasLimit"`
}

// AdditionalContract represents a contract deployed as a side effect of a transaction.
// This commonly occurs with factory deployments where the factory deploys
// contracts on behalf of the caller.
type AdditionalContract struct {
	TransactionType string `json:"transactionType"`
	Address         string `json:"address"`
	Initcode        string `json:"initcode"`
}

// DeploymentType indicates how a contract address will be created.
type DeploymentType string

const (
	DeploymentCREATE  DeploymentType = "CREATE"
	DeploymentCREATE2 DeploymentType = "CREATE2"
)

// DeploymentAddress represents a contract address to be deployed with its type.
type DeploymentAddress struct {
	Address        string         `json:"address"`
	ContractName   string         `json:"contract_name,omitempty"`
	DeploymentType DeploymentType `json:"deployment_type"`
}
