// Command api-inventory generates API_ENDPOINTS.md from the live gin route
// table (RD-1166): every registered route, the canonical operation it maps
// to, and per-method totals. This is the auditor-facing endpoint inventory;
// the OpenAPI document (make api-spec) is the full machine-readable spec.
//
// Run via `make api-inventory`. Output is deterministic so CI can regenerate
// and fail on drift.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"privacy-proxy/internal/server"
)

func main() {
	out := flag.String("out", "API_ENDPOINTS.md", "output markdown file")
	flag.Parse()

	all := server.RoutesForSpec(true)
	prod := server.RoutesForSpec(false)

	prodSet := make(map[string]bool, len(prod))
	for _, r := range prod {
		prodSet[r.Method+" "+r.Path] = true
	}

	var b strings.Builder
	b.WriteString("# Privacy Proxy — REST API Endpoint Inventory\n\n")
	b.WriteString("Generated from the live gin route table by `make api-inventory` — do not edit by hand.\n")
	b.WriteString("The machine-readable API specification is the OpenAPI document (`internal/server/apispec/swagger.json`,\n")
	b.WriteString("served at `GET /openapi.json`, generated by `make api-spec`).\n\n")

	// Group registered routes by canonical operation.
	type op struct {
		methods map[string]bool
		devOnly bool
	}
	ops := map[string]*op{} // canonical path -> op
	type aliasRow struct{ method, path, canonical, kind string }
	var aliases []aliasRow
	methodTotals := map[string]int{}

	for _, r := range all {
		methodTotals[r.Method]++
		cls := server.CanonicalizeRoute(r.Path)
		if cls.Kind != server.RouteKindCanonical {
			aliases = append(aliases, aliasRow{r.Method, r.Path, cls.Canonical, cls.Kind})
			continue
		}
		if ops[cls.Canonical] == nil {
			ops[cls.Canonical] = &op{methods: map[string]bool{}, devOnly: true}
		}
		o := ops[cls.Canonical]
		o.methods[r.Method] = true
		if prodSet[r.Method+" "+r.Path] {
			o.devOnly = false
		}
	}

	// Summary.
	b.WriteString("## Totals\n\n")
	fmt.Fprintf(&b, "- **Registered routes:** %d (production registers %d; the remainder are dev-build-only)\n", len(all), len(prod))
	fmt.Fprintf(&b, "- **Distinct operations (canonical paths):** %d — alias mounts (legacy `/api/*`, `/eth`, root auth, JSON-RPC `/`, impersonation mirrors) collapse onto these\n", len(ops))
	b.WriteString("- **Registered routes by method:** ")
	var methods []string
	for m := range methodTotals {
		methods = append(methods, m)
	}
	sort.Slice(methods, func(i, j int) bool {
		// Alphabetical tie-break: map iteration order is random, and equal
		// counts would otherwise reorder between runs, tripping the CI
		// drift check on an unchanged API surface.
		if methodTotals[methods[i]] != methodTotals[methods[j]] {
			return methodTotals[methods[i]] > methodTotals[methods[j]]
		}
		return methods[i] < methods[j]
	})
	var parts []string
	for _, m := range methods {
		parts = append(parts, fmt.Sprintf("%s %d", m, methodTotals[m]))
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString("\n\n")
	b.WriteString("Note: gin registers `.Any()` mounts (the impersonation JSON-RPC mirrors) as one route per HTTP method, so per-method totals count each of those mounts several times.\n\n")

	// Distinct operations table.
	b.WriteString("## Distinct operations\n\n")
	b.WriteString("| Method(s) | Path | Auth | Notes |\n|---|---|---|---|\n")
	var canonPaths []string
	for p := range ops {
		canonPaths = append(canonPaths, p)
	}
	sort.Strings(canonPaths)
	for _, p := range canonPaths {
		o := ops[p]
		var ms []string
		for m := range o.methods {
			ms = append(ms, m)
		}
		sort.Strings(ms)
		if len(ms) >= 7 { // .Any() mount
			ms = []string{"ANY"}
		}
		note := ""
		if o.devOnly {
			note = "dev builds only (not registered in production)"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", strings.Join(ms, ", "), p, server.AuthForPath(p), note)
	}

	// Alias table.
	b.WriteString("\n## Alias & mirror mounts (registered, collapsed above)\n\n")
	b.WriteString("| Method | Path | Documented as | Kind |\n|---|---|---|---|\n")
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].path != aliases[j].path {
			return aliases[i].path < aliases[j].path
		}
		return aliases[i].method < aliases[j].method
	})
	for _, a := range aliases {
		fmt.Fprintf(&b, "| %s | `%s` | `%s` | %s |\n", a.method, a.path, a.canonical, a.kind)
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s: %d registered routes, %d distinct operations\n", *out, len(all), len(ops))
}
