#!/usr/bin/env bash
#
# Generate a .env file with offset host ports for running parallel stacks.
#
# Usage:
#   ./scripts/stack-ports.sh [OFFSET]   # explicit offset (default: auto)
#   ./scripts/stack-ports.sh auto       # derive offset from directory name
#   ./scripts/stack-ports.sh 100        # all base ports + 100
#
# Examples:
#   ./scripts/stack-ports.sh 100 > .env            # RPC=8645, DB=5532, Proxy=8180, UI=5273
#   ./scripts/stack-ports.sh > .env                 # auto-detect from directory name
#   source <(./scripts/stack-ports.sh 200)          # load into current shell
#
# With no arguments or "auto", the offset is derived from the current directory
# name using a simple hash, yielding a stable value in 100-900 (in steps of 100).

set -euo pipefail

BASE_RPC=8545
BASE_DB=5432
BASE_PROXY=8080
BASE_UI=5173

auto_offset() {
    # Use the basename of the working directory (typically the worktree name).
    local dir_name
    dir_name="$(basename "$(pwd)")"

    # For the main checkout (common names), offset is 0.
    case "$dir_name" in
        privacy-proxy|main|master) echo 0; return ;;
    esac

    # Simple hash: sum the bytes of the directory name, mod 9, * 100 -> 100..900
    local sum=0
    local i
    for (( i=0; i<${#dir_name}; i++ )); do
        sum=$(( sum + $(printf '%d' "'${dir_name:$i:1}") ))
    done
    echo $(( (sum % 9 + 1) * 100 ))
}

offset="${1:-auto}"

if [ "$offset" = "auto" ]; then
    offset="$(auto_offset)"
fi

# Validate: must be a non-negative integer
if ! [[ "$offset" =~ ^[0-9]+$ ]]; then
    echo "Error: offset must be a non-negative integer, got '$offset'" >&2
    exit 1
fi

rpc=$(( BASE_RPC + offset ))
db=$(( BASE_DB + offset ))
proxy=$(( BASE_PROXY + offset ))
ui=$(( BASE_UI + offset ))

# Sanity check: ports must be in valid range
for port in "$rpc" "$db" "$proxy" "$ui"; do
    if (( port > 65535 )); then
        echo "Error: offset $offset produces port $port which exceeds 65535" >&2
        exit 1
    fi
done

network="privacy-proxy_proxy-network"
if (( offset != 0 )); then
    network="${network}-${offset}"
fi

cat <<EOF
# Generated by scripts/stack-ports.sh (offset=$offset)
HOST_PORT_RPC=$rpc
HOST_PORT_DB=$db
HOST_PORT_PROXY=$proxy
HOST_PORT_UI=$ui
COMPOSE_NETWORK_NAME=$network
EOF
